name: "HA Status Monitor"
version: "1.0.2"
slug: "ha_status_monitor"
description: "Reports Home Assistant to remote server every 5 minutes."

arch:
  - amd64

startup: services
boot: auto

homeassistant_api: true

options:
  api_key: ""

schema:
  api_key: password